name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set gcloud project config
        run: |
          gcloud config set project busca-med
          gcloud config set run/region southamerica-east1

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/busca-med/busca_med-web-app:$GITHUB_SHA .
          docker push gcr.io/busca-med/busca_med-web-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy busca_med-web-app \
            --image gcr.io/busca-med/busca_med-web-app:$GITHUB_SHA \
            --region southamerica-east1 \
            --platform managed \
            --allow-unauthenticated
