FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

ENV FLASK_APP=app.py 
ENV BUSCA_MED=/secrets/service_account_key.json

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"] #replace app:app if needed
