name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS1 }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'busca-med'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t southamerica-east1-docker.pkg.dev/busca-med/busca-med-web-app/busca-med-web-app:$GITHUB_SHA .
          docker push southamerica-east1-docker.pkg.dev/busca-med/busca-med-web-app/busca-med-web-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy busca-med-web-app \
            --image southamerica-east1-docker.pkg.dev/busca-med/busca-med-web-app/busca-med-web-app:$GITHUB_SHA \
            --region southamerica-east1 \
            --platform managed \
            --allow-unauthenticated

