name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2) Set up gcloud CLI and authenticate
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'busca-med'
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      # 3) Configure Docker to use gcloud as a credential helper
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      # 4) Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/busca-med/busca_med-web-app:$GITHUB_SHA .
          docker push gcr.io/busca-med/busca_med-web-app:$GITHUB_SHA

      # 5) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy busca_med-web-app \
            --image gcr.io/busca-med/busca_med-web-app:$GITHUB_SHA \
            --region southamerica-east1 \
            --platform managed \
            --allow-unauthenticated

